#!/bin/bash
if [ -n "$1" ]; then
  abspath=$(cd $(dirname $1) && pwd)/$(basename $1)
  if [ -d $abspath ]; then
    dir=$abspath
  else
    echo '"'${1}'"' is not exist.
    exit
  fi
else
  dir=`pwd`
fi

explorer.exe `wslpath -w $dir`
